const STATUS_PENDING = 1;
const STATUS_WAITING = 2;
const STATUS_CANCELED = 3;
const STATUS_COMPLETE = 4;

export { STATUS_PENDING, STATUS_WAITING, STATUS_CANCELED, STATUS_COMPLETE };
export default {
  STATUS_PENDING,
  STATUS_WAITING,
  STATUS_CANCELED,
  STATUS_COMPLETE
};
